### ISSUE TITLE
Fails on test case

### ISSUE THREAD

**Issue by chleheng** [iPapatsoris/Maximum-Independent-Set#1]
After running `git clone https://github.com/iPapatsoris/Maximum-Independent-Set.git; cd Maximum-Independent-Set; make`

On a file I added, `test.txt`:
```
# Undirected graph (each unordered pair of nodes is saved once): datasets/final/graph_100_1000.txt
# Undirected Erdos-Renyi random graph.
# Nodes: 3 Edges: 2
# NodeId	NodeId
0	1
0	2
```
Upon running `./mis test.txt`, I get the following in stdout

```
1 search nodes

Writing Maximum Independent Set to file datasets/simpletest.txt.mis
Maximum Independent Set size: 1
```
and the following output file `test.txt.mis`
```
Maximum Independent Set size: 1
0
```
(The answer should instead be nodes {0, 2} instead)

**Comment by iPapatsoris** [comment]
Hello, thanks for reporting this issue. I looked into it now and have found the bug, but by fixing it it seems that there are more bugs that I wasn't aware of. The code is quite old and would take significant time to properly make sure everything works as intended, so for the time being I will probably archive the repository.
