### ISSUE TITLE
Algorithm returns an infeasible solution

### ISSUE THREAD

**Issue by claud10cv** [iPapatsoris/Maximum-Independent-Set#4]
Hello, I have found a bug by executing your code on the problem instance
[infeas_mis.txt](https://github.com/iPapatsoris/Maximum-Independent-Set/files/14736605/infeas_mis.txt)

The solution reported by your algorithm is
```C
Maximum Independent Set size: 11
528
230
171
492
497
279
266
205
401
412
501
```

However the edge `{230, 528}` should be forbidden (I did not thoroughly check if other forbidden edges existed between the nodes in the solution)

**Comment by claud10cv** [comment]
Another example in this zip file. Edge `{132, 169}` is part of the input graph
[infeas_mis.zip](https://github.com/iPapatsoris/Maximum-Independent-Set/files/14746473/infeas_mis.zip)

**Comment by iPapatsoris** [comment]
Hello, thanks for the report. I took some time to look into the code and the research papers that it's based on, and noticed substantial deviations. Unfortunately, it would take a long time and effort to properly implement everything, as the research papers are very extensive. For the foreseeable future, I will have to archive the repository and add a note that there are bugs. Thank you for the interest.
