### ISSUE TITLE
The following file triggers an exception std::out_of_range

### ISSUE THREAD

**Issue by claud10cv** [iPapatsoris/Maximum-Independent-Set#5]
When running the following file with the code compiled in release mode (using -O3 or -O2 flags) the method triggers the following exception:
```C
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 4762) >= this->size() (which is 3)
Aborted (core dumped)
```

In debug mode (using the flag -g) the algorithm ends without triggering any exception. GDB and Valgrind catch nothing.

[infeas_mis.txt](https://github.com/iPapatsoris/Maximum-Independent-Set/files/14736797/infeas_mis.txt)

**Comment by claud10cv** [comment]
This appears to be the same issue described in #2

**Comment by iPapatsoris** [comment]
Hello, as mentioned in #4, for the foreseeable future, I will have to archive the repository. Thank you for the interest.
